### Numpy

In [1]:
#pip install numpy

In [2]:
# How to import NumPy
import numpy as np

In [3]:
# Reading the example code
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [133]:
# What is an array?
a2

array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
print(a[0])

[1 2 3 4]


In [9]:
# More information about arrays
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [10]:
# How to create a basic array
a = np.array([1, 2, 3])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.ones(2)

array([1., 1.])

In [13]:
np.empty(2)

array([1., 1.])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [16]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [18]:
# Adding, removing, and sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [20]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [22]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [24]:
array_example.ndim

3

In [25]:
array_example.size

24

In [26]:
array_example.shape

(3, 2, 4)

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [30]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [32]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [33]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [37]:
# Indexing and slicing
data = np.array([1, 2, 3])

In [38]:
data[1]

2

In [39]:
data[0:2]

array([1, 2])

In [40]:
data[1:]

array([2, 3])

In [41]:
data[-2:]

array([2, 3])

In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [43]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [44]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [45]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [46]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [48]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [49]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [50]:
print(a[b])

[1 2 3 4]


In [51]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [52]:
# How to create an array from existing data
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [54]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [55]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [56]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [57]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [59]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [63]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [64]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# Basic array operations
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [68]:
data - ones

array([0, 1])

In [69]:
data * data

array([1, 4])

In [70]:
data / data

array([1., 1.])

In [71]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [72]:
b = np.array([[1, 1], [2, 2]])

In [73]:
b.sum(axis=0)

array([3, 3])

In [74]:
b.sum(axis=1)

array([2, 4])

In [75]:
# Broadcasting
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [76]:
# More useful array operations
data.max()

2.0

In [77]:
data.min()

1.0

In [78]:
data.sum()

3.0

In [79]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [80]:
a.sum()

4.8595784

In [81]:
a.min()

0.05093587

In [82]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [83]:
# Creating matrices
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
data[0, 1]

2

In [85]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [86]:
data[0:2, 0]

array([1, 3])

In [87]:
data.max()

6

In [88]:
data.min()

1

In [89]:
data.sum()

21

In [90]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [91]:
data.max(axis=0)

array([5, 6])

In [92]:
data.max(axis=1)

array([2, 5, 6])

In [93]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [94]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [95]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [96]:
np.ones(3)

array([1., 1., 1.])

In [97]:
np.zeros(3)

array([0., 0., 0.])

In [98]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.56998889, 0.46970537, 0.35669837])

In [99]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
rng.random((3, 2)) 

array([[0.61211319, 0.6927394 ],
       [0.80283129, 0.05355139],
       [0.71819772, 0.86432065]])

In [102]:
# Generating random numbers
rng.integers(5, size=(2, 4)) 

array([[0, 3, 1, 4],
       [4, 3, 4, 3]])

In [103]:
# How to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [104]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [105]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [106]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [107]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [108]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
print(indices)

[0 1 2]


In [112]:
print(occurrence_count)

[2 1 1]


In [113]:
# Transposing and reshaping a matrix
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [117]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [118]:
# How to reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
reversed_arr = np.flip(arr)

In [120]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [121]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [122]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [123]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [124]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [125]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [126]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [127]:
# Reshaping and flattening multidimensional arrays
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [128]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [131]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
